"""Record Leo's voice: one MP3 per phrase in tools/phrases.json, plus audio/manifest.js.

Voice: Kokoro-82M (Apache-2.0), American English voice "af_heart", run locally with kokoro-onnx.
Usage:
  pip install kokoro-onnx lameenc numpy
  # model files: https://github.com/thewh1teagle/kokoro-onnx/releases/tag/model-files-v1.0
  node tools/export_phrases.js
  python3 tools/build_audio.py kokoro-v1.0.onnx voices-v1.0.bin [--all] [--redo "phrase" ...]
Existing clips are reused, so re-running only records new phrases (plus any passed with --redo,
or everything with --all). A newly recorded clip is named after its content, so browsers never
play a stale cached copy.
"""
import hashlib, json, os, re, sys
import numpy as np
import lameenc
from kokoro_onnx import Kokoro

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AUDIO = os.path.join(ROOT, 'audio')
VOICE = 'af_heart'

# Letter names, so a lone capital letter is always read as its name ("T" -> "tee").
LETTER_NAMES = {
    'A': 'ay', 'B': 'bee', 'C': 'see', 'D': 'dee', 'E': 'ee', 'F': 'eff', 'G': 'jee', 'H': 'aitch', 'J': 'jay',
    'K': 'kay', 'L': 'el', 'M': 'em', 'N': 'en', 'O': 'oh', 'P': 'pee', 'Q': 'cue', 'R': 'ar', 'S': 'ess', 'T': 'tee',
    'U': 'you', 'V': 'vee', 'W': 'double you', 'X': 'ex', 'Y': 'why', 'Z': 'zee',
}
# Phrases spoken from different text.
OVERRIDES = {
    'a': 'uh.',  # the sight word "a" is said "uh", not the letter name
}


def tts_text(phrase):
    if phrase in OVERRIDES:
        return OVERRIDES[phrase]
    t = re.sub(r'\b([Mm]agic) e\b', r'\1 ee', phrase)

    def letter(m):
        # "A monkey!" starts with the article; "A is for apple" and "A, magic e" use the letter name
        if m.group(1) == 'A' and m.start() == 0 and re.match(r' (?!is\b)[a-z]', t[m.end():]):
            return 'A'
        return LETTER_NAMES[m.group(1)]

    t = re.sub(r'\b([A-HJ-Z])\b', letter, t)
    # a lone word sounds complete (not cut off) when it ends like a sentence
    if not re.search(r'[.!?:]$', t):
        t += '.'
    return t


def clip_name(mp3):
    return hashlib.sha1(mp3).hexdigest()[:12] + '.mp3'


def old_manifest():
    path = os.path.join(AUDIO, 'manifest.js')
    if not os.path.exists(path):
        return {}
    return json.loads(open(path, encoding='utf-8').read().split('=', 1)[1].strip().rstrip(';'))


def to_mp3(pcm, rate):
    x = np.asarray(pcm, dtype=np.float32)
    # trim silence at both ends (relative to the peak, so quiet final consonants survive), keep a pad
    peak = np.abs(x).max() or 1.0
    loud = np.where(np.abs(x) > 0.01 * peak)[0]
    if len(loud):
        pad = int(0.07 * rate)
        x = x[max(0, loud[0] - pad): loud[-1] + pad]
    x = np.clip(x * (0.89 * 32767 / peak), -32767, 32767).astype(np.int16)
    enc = lameenc.Encoder()
    enc.set_bit_rate(48)
    enc.set_in_sample_rate(rate)
    enc.set_channels(1)
    enc.set_quality(2)
    return enc.encode(x.tobytes()) + enc.flush()


def main(model, voices, redo=(), everything=False):
    kokoro = Kokoro(model, voices)
    phrases = json.load(open(os.path.join(ROOT, 'tools', 'phrases.json')))
    os.makedirs(AUDIO, exist_ok=True)
    old = {} if everything else old_manifest()
    manifest, made = {}, 0
    for ph in phrases:
        if ph in old and ph not in redo and os.path.exists(os.path.join(AUDIO, old[ph])):
            manifest[ph] = old[ph]
            continue
        speed = 0.85 if len(ph.split()) <= 2 else 0.92  # single words a little slower
        pcm, rate = kokoro.create(tts_text(ph), voice=VOICE, speed=speed, lang='en-us')
        mp3 = to_mp3(pcm, rate)
        manifest[ph] = clip_name(mp3)
        with open(os.path.join(AUDIO, manifest[ph]), 'wb') as f:
            f.write(mp3)
        made += 1
    # remove clips no longer used
    keep = set(manifest.values())
    for f in os.listdir(AUDIO):
        if f.endswith('.mp3') and f not in keep:
            os.remove(os.path.join(AUDIO, f))
    with open(os.path.join(AUDIO, 'manifest.js'), 'w', encoding='utf-8') as f:
        f.write('// Generated by tools/build_audio.py: phrase -> recorded clip\n')
        f.write('window.PHONICS_CLIPS = ' + json.dumps(manifest, ensure_ascii=False, indent=0) + ';\n')
    print(f'{len(phrases)} phrases, {made} new clips')


if __name__ == '__main__':
    args = sys.argv[1:]
    redo = set(args[args.index('--redo') + 1:]) if '--redo' in args else set()
    args = args[:args.index('--redo')] if '--redo' in args else args
    everything = '--all' in args
    args = [a for a in args if a != '--all']
    if len(args) < 2:
        sys.exit(__doc__)
    main(args[0], args[1], redo, everything)
