"""Record Leo's voice: one MP3 per phrase in tools/phrases.json, plus audio/manifest.js.

Voice: Piper TTS with the public-domain LJSpeech voice (en_US-ljspeech-high).
Usage:
  pip install piper-tts lameenc numpy
  node tools/export_phrases.js
  python3 tools/build_audio.py path/to/en_US-ljspeech-high.onnx
Existing clips are reused, so re-running only records new phrases.
"""
import hashlib, json, os, re, sys
import numpy as np
import lameenc
from piper import PiperVoice
from piper.config import SynthesisConfig

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AUDIO = os.path.join(ROOT, 'audio')

# Letter names, so a lone capital letter is read as its name ("T" -> "tee").
LETTER_NAMES = {
    'A': 'ay', 'B': 'bee', 'C': 'see', 'D': 'dee', 'E': 'ee', 'F': 'eff', 'G': 'jee', 'H': 'aitch', 'J': 'jay',
    'K': 'kay', 'L': 'el', 'M': 'em', 'N': 'en', 'O': 'oh', 'P': 'pee', 'Q': 'cue', 'R': 'ar', 'S': 'ess', 'T': 'tee',
    'U': 'you', 'V': 'vee', 'W': 'double you', 'X': 'ex', 'Y': 'why', 'Z': 'zee',
}
# Phrases spoken from phonemes instead of text.
PHONEMES = {
    'a': ['ˈ', 'ʌ'],  # the sight word "a" is said "uh", not the letter name
}


def tts_text(phrase):
    t = re.sub(r'\bmagic e\b', 'magic ee', phrase)
    t = re.sub(r'\b([A-HJ-Z])\b', lambda m: LETTER_NAMES[m.group(1)], t)
    return t


def clip_name(phrase):
    return hashlib.sha1(phrase.encode('utf-8')).hexdigest()[:12] + '.mp3'


def to_mp3(pcm, rate):
    x = pcm.astype(np.float32)
    # trim silence at both ends, keep a short pad
    loud = np.where(np.abs(x) > 400)[0]
    if len(loud):
        pad = int(0.04 * rate)
        x = x[max(0, loud[0] - pad): loud[-1] + pad]
    peak = np.abs(x).max() or 1.0
    x = np.clip(x * (0.89 * 32767 / peak), -32767, 32767).astype(np.int16)
    enc = lameenc.Encoder()
    enc.set_bit_rate(48)
    enc.set_in_sample_rate(rate)
    enc.set_channels(1)
    enc.set_quality(2)
    return enc.encode(x.tobytes()) + enc.flush()


def main(model):
    voice = PiperVoice.load(model)
    rate = voice.config.sample_rate
    phrases = json.load(open(os.path.join(ROOT, 'tools', 'phrases.json')))
    os.makedirs(AUDIO, exist_ok=True)
    manifest, made = {}, 0
    for ph in phrases:
        name = clip_name(ph)
        manifest[ph] = name
        out = os.path.join(AUDIO, name)
        if os.path.exists(out):
            continue
        words = len(ph.split())
        cfg = SynthesisConfig(length_scale=1.18 if words <= 2 else 1.07, noise_scale=0.6, noise_w_scale=0.7)
        if ph in PHONEMES:
            ids = voice.phonemes_to_ids(PHONEMES[ph])
            pcm = voice.phoneme_ids_to_audio(ids, cfg)
            pcm = np.asarray(pcm)
            if pcm.dtype != np.int16:
                pcm = (np.clip(pcm, -1, 1) * 32767).astype(np.int16)
        else:
            pcm = np.concatenate([np.frombuffer(c.audio_int16_bytes, dtype=np.int16) for c in voice.synthesize(tts_text(ph), cfg)])
        with open(out, 'wb') as f:
            f.write(to_mp3(pcm, rate))
        made += 1
    # remove clips no longer used
    keep = set(manifest.values())
    for f in os.listdir(AUDIO):
        if f.endswith('.mp3') and f not in keep:
            os.remove(os.path.join(AUDIO, f))
    with open(os.path.join(AUDIO, 'manifest.js'), 'w', encoding='utf-8') as f:
        f.write('// Generated by tools/build_audio.py: phrase -> recorded clip\n')
        f.write('window.PHONICS_CLIPS = ' + json.dumps(manifest, ensure_ascii=False, indent=0) + ';\n')
    print(f'{len(phrases)} phrases, {made} new clips')


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else 'en_US-ljspeech-high.onnx')
